### ISSUE TITLE
--min_length argument is not work

### ISSUE THREAD

**Issue by Litterlemon** [tjiangHIT/rMETL#5]
https://github.com/tjiangHIT/rMETL/blob/cad864700727d71c47be9b13ba47002d8e773c27/src/rMETL_extraction.py#L228
hi，thank you for your job,that is contribute to my project.But also i have a question about you script.such as def parse_read(read, Chr_name, low_bandary, CLIP_note) in RMETL_extraction.py,why is low_bandary but not SV_size?

**Comment by tjiangHIT** [comment]
Hi @Litterlemon 
Thank you for using rMETL!
The parameter --min_length is uesd in ME candidate clustering and named as **_SV_size_**.
https://github.com/tjiangHIT/rMETL/blob/cad864700727d71c47be9b13ba47002d8e773c27/src/rMETL_extraction.py#L328
In the function **_parse_read_**, rMETL extract all of insertion and deletion signatures with **_low_bandary_** in order to acquire more fine signals for ME detecting sensitively. However, in the function **_cluster_**, rMETL wants to generate high quality MEI or MED candidates and avoid false positive caused by wrong signals, so rMETL uses the more stringent  parameter **_SV_size_**. Besause of this designing, rMETL can identify more non-reference MEI/MED with sensitive and accuracy.
Please do not hesitate to let me know if you have any question or concern. 
Best wishes,
Tao

**Comment by tjiangHIT** [comment]
Hi @Litterlemon 
Thank you for using rMETL!
The parameter --min_length is uesd in ME candidate clustering and named as **_SV_size_**.
https://github.com/tjiangHIT/rMETL/blob/cad864700727d71c47be9b13ba47002d8e773c27/src/rMETL_extraction.py#L328
In the function **_parse_read_**, rMETL extract all of insertion and deletion signatures with **_low_bandary_** in order to acquire more fine signals for ME detecting sensitively. However, in the function **_cluster_**, rMETL wants to generate high quality MEI or MED candidates and avoid false positive caused by wrong signals, so rMETL uses the more stringent  parameter **_SV_size_**. Besause of this designing, rMETL can identify more non-reference MEI/MED with sensitive and accuracy.
Please do not hesitate to let me know if you have any question or concern. 
Best wishes,
Tao
